### ISSUE TITLE
Implementing indicators

### ISSUE THREAD

**Issue by gambitov** [kaelzhang/stock-pandas-examples#1]
Dear developer,

I have been reading the examples and I have notice that:

the data have `time_key	open close high low volume turnover pe_ratio turnover_rate last_close`
my data just have `[Date, Open, High, Low, Close, Volume]`

when I use the next code:
```
datafile = 'ohclv.csv'
stock = StockDataFrame(pd.read_csv(datafile, index_col = 'Date'))
stock['ma:5']
```

I am getting this error.

```
Exception has occurred: DirectiveValueError
File "<string>", line 1, column 1
>  close
   ^
DirectiveSyntaxError: unknown command "close"
```

May you help me? please.

**Comment by kaelzhang** [comment]
Nice catch ~

It is an issue that stock-pandas does not provide the proper error hint.

And the root cause of the error is that stock-pandas uses the lowercased column name `close`.

### Solutions

Tips:
1. stock-pandas requires lowercased column name `open`, `close`, `high` and `low`
2. but `mplfinance` requires uppercased column names.

To fix the conflicts, we could use the `stock.alias` method of stock-pandas.

First of all, you need to upgrade stock-pandas

```sh
pip install -U stock-pandas
```

```py
datafile = 'ohclv.csv'
stock = StockDataFrame(pd.read_csv(datafile, index_col = 'Date'))

stock.alias('open', 'Open')
stock.alias('high', 'High')
stock.alias('low', 'Low')
stock.alias('close', 'Close')

print(stock['ma:20'])
```

You could check the jupyter notebook to figure out how to plot grams

**Comment by gambitov** [comment]
deat @kaelzhang , I was using your code but it does not work, i am getting next error
```
ma:20 not found.
KeyError: 'ma:20'
```

**Comment by gambitov** [comment]
dear @kaelzhang, thank you so much it works perfectly. Could you help me to add subplots? I want to plot ema:10 and histogram of MACD and ADX.

**Comment by kaelzhang** [comment]
I've updated the comment above
